### ISSUE TITLE
Column remove not working 100% of time

### ISSUE THREAD

**Issue by ErinTanaka** [cs361fall2017/team23#61]
I was doing a test run with the Spanish deck and wanted to remove a card from the first column. I ended up with an error from the jquery. I have no clue where it came from or if it was a specific state that the game was in because afterwards everything played fine.

**Comment by padalah** [comment]
I was trying to duplicate this issue and I ran the program but I am not running into this issue. I am able to remove a Spanish deck card from the first column.

**Comment by padalah** [comment]
It was probably that specific state...Can you be more clear on how you ran into it?

**Comment by ErinTanaka** [comment]
![image](https://user-images.githubusercontent.com/26945774/33452794-3b91c36a-d5c8-11e7-9e6a-ca4b2e691b58.png)

Hopefully this is a screen shot of it. I removed a card from column 4 and then tried to remove form column 2 but can't. No error mssg pops up or anything,

**Comment by ErinTanaka** [comment]
Happened again here, After the first deal, I removed a card. Then there was a second card that I wanted to remove but couldn't. The game gets a server error. If I hit the deal button it deals four cards and i can keep playing as if nothing happened. Cards get removed and error messages pop up as if nothing went wrong earlier.
![image](https://user-images.githubusercontent.com/26945774/33452968-cdc02308-d5c8-11e7-99cf-959512a9778f.png)

**Comment by padalah** [comment]
I ran into a similar problem during Sprint 1 or 2 for the standard deck. Can you check if there is a similar problem on standard deck? If there is then it is a deeper problem with the code. We can try to fix it but I don't believe it is priority 1.

**Comment by ErinTanaka** [comment]
Standard deck is fine I kept starting new games and whenever I started a game that i could remove two cards after the first deal it let me do it, no problem.

There was a 9 of diamonds in column 2 and an 8 of diamonds in column 3, worked fine.
![image](https://user-images.githubusercontent.com/26945774/33454049-72c9fc0e-d5cc-11e7-919f-1fff3efabef8.png)
3 of hearts and 6 of diamonds both removed fine
![image](https://user-images.githubusercontent.com/26945774/33454097-9f32f160-d5cc-11e7-81ca-ae107a4bdaea.png)
8 clubs and 4 spades fine
![image](https://user-images.githubusercontent.com/26945774/33454179-e7df6c90-d5cc-11e7-876c-b51966cd1e7a.png)
J and 5 of spades successful
![image](https://user-images.githubusercontent.com/26945774/33454292-434a8812-d5cd-11e7-8c2d-c64c015d39ec.png)

**Comment by ErinTanaka** [comment]
Fixed it,pull request is up
